services:
  - type: web
    name: richmenu-bot
    env: python
    buildCommand: ""
    startCommand: python main.py
    plan: free
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        value: ""
